### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by basgren**
Hi Anna. 
First, thank you for the great amount of work done! It saved me a lot of time.

To improve usability of the library, I have added bower support to make it easier to include your library in other projects.

While in lib directory d3 v3.5 was used for examples, I had to use 3.3 version in bower dependencies to avoid conflict with d3.chart dependency.

Also it would be nice to publish the library in bower repository, but before I suggest renaming package name from 'd3.chart.layout' to 'd3.chart.layout.hierarchy' to better reflect its purpose. What do you think?

### CODE REVIEW

**Comment by bansaghi** [comment]
Hi Basil,
You are very welcome, and thank you very much for the Bower support.

About renaming the package and publishing in Bower:
Yes, renaming makes sense. I used to think about implementing more layouts, but I have to admit that I will not develop them. So I will publish it with the name 'd3.chart.layout.hierarchy'.

Thoughts about version conflict:
I am very new to Bower, actualy I payed more attention on it after your comment. In a long term basis I would like to add dependency on the latest version of 'd3.js'. Recently I do not know how to achieve this in Bower. Maybe I should fork the 'd3.chart' package and maintain it myself.

(Finally, there will be some modifications in the source folder structure. It will reflect to [M. Bostock's layout folder] (https://github.com/mbostock/d3/tree/master/src/layout).)

**Comment by basgren** [comment]
Thank you for the merge! :) 
I see you already changed repository name, and that's great! So if you don't mind, I can prepare bower manifest for publishing.

**Comment by bansaghi** [comment]
Of course, you made a nice enhancement! Yes, pleae, create that file.

**Comment by bansaghi** [comment]
I got it: bower.json IS the manifest file :)
I have published the package to Bower, and would like to say thank you again Basil, for your valuable suggestions and contribution.

**Comment by basgren** [comment]
I'm glad that you published the library! Congrats with the first Bower release!)

**Pull request merged**
